# Python stubs generated by omniidl from soma.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Example"
#
__name__ = "Example"
_0_Example = omniORB.openModule("Example", r"soma.idl")
_0_Example__POA = omniORB.openModule("Example__POA", r"soma.idl")


# interface Soma
_0_Example._d_Soma = (omniORB.tcInternal.tv_objref, "IDL:Example/Soma:1.0", "Soma")
omniORB.typeMapping["IDL:Example/Soma:1.0"] = _0_Example._d_Soma
_0_Example.Soma = omniORB.newEmptyClass()
class Soma :
    _NP_RepositoryId = _0_Example._d_Soma[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Example.Soma = Soma
_0_Example._tc_Soma = omniORB.tcInternal.createTypeCode(_0_Example._d_Soma)
omniORB.registerType(Soma._NP_RepositoryId, _0_Example._d_Soma, _0_Example._tc_Soma)

# Soma operations and attributes
Soma._d_calcularSoma = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float), (omniORB.tcInternal.tv_float, ), None)

# Soma object reference
class _objref_Soma (CORBA.Object):
    _NP_RepositoryId = Soma._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def calcularSoma(self, *args):
        return self._obj.invoke("calcularSoma", _0_Example.Soma._d_calcularSoma, args)

omniORB.registerObjref(Soma._NP_RepositoryId, _objref_Soma)
_0_Example._objref_Soma = _objref_Soma
del Soma, _objref_Soma

# Soma skeleton
__name__ = "Example__POA"
class Soma (PortableServer.Servant):
    _NP_RepositoryId = _0_Example.Soma._NP_RepositoryId


    _omni_op_d = {"calcularSoma": _0_Example.Soma._d_calcularSoma}

Soma._omni_skeleton = Soma
_0_Example__POA.Soma = Soma
omniORB.registerSkeleton(Soma._NP_RepositoryId, Soma)
del Soma
__name__ = "Example"

#
# End of module "Example"
#
__name__ = "soma_idl"

_exported_modules = ( "Example", )

# The end.
